#!/bin/zsh
vim () {
	needsu() {
		test $(stat -c %u $1:a) -eq 0
	}
	if for a in $@
		do
			needsu $a 2>/dev/null && break
		done
	then
		printf "\e[97;41muse sudo?\e[0m "
		if read -qs "?[y/N]"
		then
			printf "\n\e[92musing sudo\e[0m\n"
			local su="sudo"
			read -t 1
		fi
	fi
	eval $su /usr/bin/vim $@
}
